### ISSUE TITLE
Do I need the 2N7000

### ISSUE THREAD

**Issue by yepeekai** [Kaldek/rat-ratgdo#30]
I don't know much about those components.  I trust your judgment to change one of the 2N7000 to a rfp30n06le.  My question is: could I change both to rfp30n06le?  In my case, I don't have either components so I need to order both... In both cases, it doesn't make sense to order only one so if rfp30n06le is better and is compatible to replace both 2N7000, I would keep things simple and only order rfp30n06le.

Thanks

**Comment by Kaldek** [comment]
The original ratgdo uses a 2n700X for the RX MOSFET so I'd stick with that.  The gate voltage on the RX MOSFET will be 12 volts, whereas the gate volate on the TX MOSFET will be 3.3v (driven by the ESP).  The reason for the use of an AO3400A as the surface mount TX MOSFET is because it has better switching reliability for a 3.3v gate voltage.   Current guidance is 2n7000 for RX and the RFP30N06LE for TX, but any MOSFET which can be driven with 3.3v, switch 12v and draw very little current when doing so will work.
