### ISSUE TITLE
POE?

### ISSUE THREAD

**Issue by benrabicoff** [Kaldek/rat-ratgdo#59]
Is there a possibility to use a board that supports ethernet/POE?

**Comment by rlowens** [comment]
I haven't seen anyone say they have, but it is still just an ESP chip communicating with GPIOs so it shouldn't matter at all.

I don't think the ratgdo firmware uses a particularly large amount of RAM/storage/CPU so loading ethernet drivers at the same time shouldn't be a problem.

Let us know if you do!

**Comment by baylanger** [comment]
@benrabicoff You want the POE just to power the device or power & use the network cable instead of WiFi?

If you only need the power, you can buy a POE adapter that splits into a network cable and USB-C port (5V). If you have a POE network switch, make sure the adapter can handle the switch's power (48V vs 57V at the network switch's port). If you don't have a POE switch, buy 2 adapters and inject 5V.

**Comment by benrabicoff** [comment]
@baylanger Looking to power and use the device over ethernet. Looking into something like: https://www.mouser.com/ProductDetail/Olimex-Ltd/ESP32-POE-ISO?qs=sGAEpiMZZMuqBwn8WqcFUj2aNd7i9W7uc087HzBKguU1UBkflb3j3w%3D%3D

**Comment by baylanger** [comment]
Oh that is a very nice board, obviously it exists... I had just woke up when I replied earlier :D

Not sure how much work is needed to add the POE port. Maybe board v3 could be slightly bigger to support either w/ or w/o the POE port, this gives the option to ask the fabric to make a batch of boards but at assembly a percentage would get the POE parts.

Otherwise quickly a solution is to use a POE adapter w/ a micro-USB output (not USB-C like I mentioned above, now edited).

Adding [Ethernet support](https://esphome.io/components/ethernet.html) is easy.

**Comment by xrxca** [comment]
I've been experimenting with LilyGo's T-Internet-POE, it's sort-of been working jumpered to a breadboard ratgdo using GPIO 16, 32 and 33
Sort of means I've got intermittent connection issues, and a weirdness with the obstruction line I can't figure out.  If I connect it I can't close the door even from the wall panel as it always flashes sensing an obstruction, could be an issue on the breadboard, or it may be an issue with the existing wiring but the opener works perfectly when the black wire is not connected to the ratgdo.
So basically I've only got red and white connected, which seems to work.
I've created a tiny (25x25) board based on the schematics here using easyeda that has a 3 wire connector for the GDO wires, and a 4 pin connector that I can jumper to the ESP of my choice, and having a few different ESP options in my parts bin, will experiment more when the boards arrive from jlcpcb.
(If I'd looked at this earlier I'd probably have ordered one from Paul, but since his current version has the ESP integrated, it's useless for trying to get a POE version running.)

**Comment by baylanger** [comment]
> I've been experimenting with LilyGo's T-Internet-POE, it's sort-of been working jumpered to a breadboard ratgdo using GPIO 16, 32 and 33

@xrxca there are pins that requires pull up, is your config covering that? Without that config, the input is floating.

https://esphome.io/components/binary_sensor/gpio.html

**Comment by Kaldek** [comment]
Closing as this just needs to be solved by those interested and raised as a subsequent Pull Request.
