### ISSUE TITLE
Which board should I use?

### ISSUE THREAD

**Issue by mikekay1** [Kaldek/rat-ratgdo#7]
Hello, and Thank you all for this amazing work. I also am trying to do this because of MyQs API fumbles and want to control locally, but cannot wait for a back order to complete. Didnt know this existed until 12h ago, and will build for friends that need this!

A few questions:
1. I have an ESP32 and ESP8266 nodemcu which one is better suited? From reading its the ESP32?
2. Which firmware works best for security 2.0+ garage door, from reading I think its 2.0 because I dont require dry contact function correct?
3. How to donate to cause for everyones time, paypal, buymecoffe, buymebeer link.

Thanks,

**Comment by Kaldek** [comment]
Hi mate the ESP32 is massive overkill (no insult to the folks who have already used one!), so use an ESP8266.  Quickest and easiest option is to buy a ESP8266 D1 Mini as it has the USB port and all the pins labelled for you.

**Comment by mikekay1** [comment]
Totally is over kill you are right, but its what I got lying around so it's not like I am going out and buying the boards. Wifey doesn't like the amazon purchases lately :)

Id like to donate, where can I send?

**Comment by mikekay1** [comment]
https://www.amazon.ca/CANADUINO-WEMOS-ESP8266-Wi-Fi-Module/dp/B07WWFND3B/ref=sr_1_2?crid=282XO0OXQOL3C&keywords=d1+mini&qid=1698450042&sprefix=d1+mini%2Caps%2C80&sr=8-2

that would work correct?

**Comment by rlowens** [comment]
1. I agree that the ESP8266 is sufficient for this, if you aren't adding any other sensors/display which you need the extra GPIOs for.
The nodemcu board you already have should work fine (it has the same labels as the D1 mini so you don't even need translate the pin labels).

2. If you are using the ESPHome firmware, it only supports Security+ 2.0 anyway. The Security+ 1.0 and Dry Contact support hasn't been migrated to the ESPHome version yet. And regardless, the "2.0 vs. 2.5" difference is just 1 pin assignment. Might as well use the pins that the "2.5" version expects in case that ever matters for ease of upgrading firmware if ever needed.

3. Have no idea how you could donate to Kaldek in support of his work here.

4. Yes, that ESP8266 D1 Mini board would work, or the nodemcu you already have.

**Comment by mikekay1** [comment]
Guys Im a bit lost which what the connects connect to on the garage door opener side. I know ai have the circuit correct or think I do. But the wall panel doesnt even work at all now. Can someone help a brother out?

**Comment by Kaldek** [comment]
> Id like to donate, where can I send?

I've thought about offering the ability to "Toss a Coin to your Witcher" purely to help cover some of the hardware costs.  I, ahem, spent more than it costs to get a ratgdo kit shipped to me to get this working.  However I did manage to do it in two days rather than 4 weeks of backorder so there's that!

Let me look into that in a manner which doesn't seem greedy or an attempt to pull funds away from Paul Wieland.  Whilst I don't agree with his refusal to offer the schematics, he **did* put in a LOT of time into the code and the Security+ protocol.  For those that can wait for a board, they should buy one from him.

However, it does look like we're going to end up with schematic files here which can be sent to places like PCBWay or JLCPCB for rapid local printing of your own board.  Whilst that wasn't my original intent, and it means somebody could go and start printing the PCBs in volume (which would directly undercut Paul's income).  Realistically thought, if that was going to happen it would happen regardless of that content existing within this repo.
