### ISSUE TITLE
Convert v2 board to v2.5?

### ISSUE THREAD

**Issue by tfcarlin** [Kaldek/rat-ratgdo#8]
I'd like to update a v2.0 shield to v2.5. It is as simple as removing the R3 resistor and adding a 10k resistor between d1 and the "output" side of R3?

THANKS!

**Comment by rlowens** [comment]
As far as we know, yes. Either remove R3 (so that D4 is not connected) and connect a 10k resistor between D1 and the "output" pad of R3, or cut the trace between R3 and D4 and add a bodge wire from the "input" pad of R3 to D1.

We haven't seen any pictures of the front of ratgdo v2.5 to trace where anything new may have been added. From the programming side, changing from D4 to D1 is the only change we know of.

Reference for others reading this discussion, this is the ratgdo v2.0:
![image](https://github.com/Kaldek/rat-ratgdo/assets/35885181/0951d536-b1e5-41c5-885e-ab499d03ee3e)
![image](https://github.com/Kaldek/rat-ratgdo/assets/35885181/cdb2021f-7139-4575-9ca1-1973bdc48409)

**Comment by Kaldek** [comment]
@tfcarlin since you have a board in hand can you do some probing with a multimeter in resistance mode for us?

Please do the following two probes and provide the resistance values here if you can!
![image](https://github.com/Kaldek/rat-ratgdo/assets/26052829/54361357-52df-4480-b44e-df7486a060f7)

**Comment by tfcarlin** [comment]
Both the green and red arrows report 0.

**Comment by Kaldek** [comment]
> Both the green and red arrows report 0.

Can you do the green one again sorry but from the other side of the resistor?  So it's from the white wire terminal to the left side of that resistor.

**Comment by Kaldek** [comment]
> Both the green and red arrows report 0.

Can you do the green one again sorry but from the other side of the resistor?  So it's from the white wire terminal to the left side of that resistor.

**Comment by Kaldek** [comment]
Paging @tfcarlin !

**Comment by tfcarlin** [comment]
Unfortunately I have since converted my 2.0 shield to have a 10k resistor between d1 and the output of R3 (and thus removed the 10k resistor surface mounted at R3). So my readings might be corrupt. With that caveat, both Red and Green arrows read 0L on my Fluke 179.

**Comment by Kaldek** [comment]
Cheers, thanks for putting in the time anyway!
