### ISSUE TITLE
not working with the code

### ISSUE THREAD

**Issue by denveronly** [Kaldek/rat-ratgdo#90]
Hey there,
Thanks for great work, so i followed and made a pcb, soldered it and got flashed.

I have Security 2.0 GDO
![photo_2024-02-15_20-55-45](https://github.com/Kaldek/rat-ratgdo/assets/66441516/4d6e0689-a2e1-431a-99fb-8770e7ec811c)
The board i used is D1 8266. With the pins like in the project soldered.
I flashed this code.  And have it working partialy...
1) I can open and close
2) i can't stop or open\close partially (tried full close and full open several times)
3) i see obstruction 
4) i really can only open and close and see obstruction, no other functions are visible

![image](https://github.com/Kaldek/rat-ratgdo/assets/66441516/f989e75f-859f-436a-b4d1-f617d017416e)

![image](https://github.com/Kaldek/rat-ratgdo/assets/66441516/cf926ba6-14a5-4d98-9069-7012844ad9f1)

![viber_image_2024-02-14_16-04-32-939](https://github.com/Kaldek/rat-ratgdo/assets/66441516/5ccd9c81-ead0-4db7-8d2a-8693c5ab7cf3)
![viber_image_2024-02-13_16-36-52-922](https://github.com/Kaldek/rat-ratgdo/assets/66441516/b2123365-6b88-4f0e-bb3e-1686080e7d7d)

![photo_2024-02-15_20-56-00](https://github.com/Kaldek/rat-ratgdo/assets/66441516/d7fa797e-eb0a-422d-9f06-7f1c70f0a1a5)
![photo_2024-02-15_20-55-56](https://github.com/Kaldek/rat-ratgdo/assets/66441516/cd6263df-2248-43fb-b32e-fbd170de3506)
![photo_2024-02-15_20-55-54](https://github.com/Kaldek/rat-ratgdo/assets/66441516/332761d5-1426-4715-a4e3-946b5e49e09b)
![photo_2024-02-15_20-55-51](https://github.com/Kaldek/rat-ratgdo/assets/66441516/d6d041e2-90c6-4419-bd9d-b908272fbe44)

**Comment by denveronly** [comment]
Maybe it is the way it should be?
I added manually seconds of Closing and Open Time (16sec)
And i have closed and open States, i can close and open partially

Or it should be automatic?

**Comment by rlowens** [comment]
Several problems here.
First off, you board is wired wrong:
![image](https://github.com/Kaldek/rat-ratgdo/assets/35885181/fecc301a-b08e-4c4c-a959-d7c78afc18ce)


![image](https://github.com/Kaldek/rat-ratgdo/assets/35885181/5ea5c509-7296-4b71-a233-03e99d3dd99e)

Obst pin (D7 by default but you used D0, which should work I think but you need to specify it in your device .yaml which I don't think you did) is supposed to be connected as a voltage divider between GDO Obst wire and GND, but you thought a cross-over in the schematic was a junction and connected it to part of the D1 tx line instead of GND.

Second, in the firmware: you have a security+ 2.0 GDO but are using security+ 1.0 firmware? I'm surprised this is working at all.
![image](https://github.com/Kaldek/rat-ratgdo/assets/35885181/51a874d5-b63c-4789-a402-52ef70ba6b80)

You want "v25board_esp8266_d1_mini.yaml@main"

I think if you cut that bad trace and connect as I indicated it should work. Also need to specify in your yaml 

```
substitutions:
  input_obst_pin: D0
  status_door_pin: none
```

**Comment by ashishgururani** [comment]
@denveronly did you figure this out? I am having the same issue here https://github.com/Kaldek/rat-ratgdo/issues/91

**Comment by Kaldek** [comment]
Closing due to lack of updates.
